In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Social_Network_Ads.csv')
df.head(2)

User ID Gender  Age  EstimatedSalary  Purchased
0  15624510   Male   19            19000          0
1  15810944   Male   35            20000          0

In [3]:
df=df.drop('User ID',axis=1)
df.head(2)

Gender  Age  EstimatedSalary  Purchased
0   Male   19            19000          0
1   Male   35            20000          0

In [4]:
df=pd.get_dummies(df,drop_first=True).astype(int)
df.head(3)

Age  EstimatedSalary  Purchased  Gender_Male
0   19            19000          0            1
1   35            20000          0            1
2   26            43000          0            0

In [5]:
df.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [6]:
indep = df[['Age', 'EstimatedSalary', 'Gender_Male']]
dep = df[['Purchased']]

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(indep,dep,test_size=1/3,random_state=0)

In [8]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train,y_train.values.ravel())
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
CM = confusion_matrix(y_test,y_pred)
print(CM)
from sklearn.metrics import classification_report
CF = classification_report(y_test,y_pred,zero_division=0)
print(CF)

[[80  5]
 [ 8 41]]
              precision    recall  f1-score   support

           0       0.91      0.94      0.92        85
           1       0.89      0.84      0.86        49

    accuracy                           0.90       134
   macro avg       0.90      0.89      0.89       134
weighted avg       0.90      0.90      0.90       134



In [9]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train,y_train.values.ravel())
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
CM = confusion_matrix(y_test,y_pred)
print(CM)
from sklearn.metrics import classification_report
CF = classification_report(y_test,y_pred,zero_division=0)
print(CF)

[[85  0]
 [49  0]]
              precision    recall  f1-score   support

           0       0.63      1.00      0.78        85
           1       0.00      0.00      0.00        49

    accuracy                           0.63       134
   macro avg       0.32      0.50      0.39       134
weighted avg       0.40      0.63      0.49       134



In [10]:
from sklearn.naive_bayes import ComplementNB
classifier = ComplementNB()
classifier.fit(X_train,y_train.values.ravel())
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
CM = confusion_matrix(y_test,y_pred)
print(CM)
from sklearn.metrics import classification_report
CF = classification_report(y_test,y_pred,zero_division=0)
print(CF)

[[40 45]
 [20 29]]
              precision    recall  f1-score   support

           0       0.67      0.47      0.55        85
           1       0.39      0.59      0.47        49

    accuracy                           0.51       134
   macro avg       0.53      0.53      0.51       134
weighted avg       0.57      0.51      0.52       134



In [11]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train,y_train.values.ravel())
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
CM = confusion_matrix(y_test,y_pred)
print(CM)
from sklearn.metrics import classification_report
CF = classification_report(y_test,y_pred,zero_division=0)
print(CF)

[[85  0]
 [49  0]]
              precision    recall  f1-score   support

           0       0.63      1.00      0.78        85
           1       0.00      0.00      0.00        49

    accuracy                           0.63       134
   macro avg       0.32      0.50      0.39       134
weighted avg       0.40      0.63      0.49       134



In [12]:
from sklearn.naive_bayes import CategoricalNB
classifier = CategoricalNB()
classifier.fit(X_train,y_train.values.ravel())
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
CM = confusion_matrix(y_test,y_pred)
print(CM)
from sklearn.metrics import classification_report
CF = classification_report(y_test,y_pred,zero_division=0)
print(CF)

[[82  3]
 [18 31]]
              precision    recall  f1-score   support

           0       0.82      0.96      0.89        85
           1       0.91      0.63      0.75        49

    accuracy                           0.84       134
   macro avg       0.87      0.80      0.82       134
weighted avg       0.85      0.84      0.84       134

